export const INCREMENT='INCREMENT';
export const DESCKREMENT='DESCKREMENT';
export const INPUT_TEXT='INPUT_TEXT';
export const COMMENT_CREATE='COMMENT_CREATE';
export const UPDATE_COMMENT='UPDATE_COMMENT';
export const DELETE_COMMENT='DELETE_COMMENT';

export const COMMENTS_LOADER='COMMENTS_LOADER';
export const LOADER_DISPLAY_ON='LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF='LOADER_DISPLAY_OFF'